# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWinUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# move_right_border
mrb = 17


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042+mrb, 557)
        MainWindow.setStyleSheet("#mainWin, #titleBar, #tableWidget_table\n"
"{\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"/*Границы между клетками*/\n"
"QTableWidget\n"
"{\n"
"gridline-color: rgb(16, 200, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"text-align: center;\n"
"}\n"
"\n"
"QFrame QWidget{\n"
"font-family: sans-serif;\n"
"font-family: Pristina;\n"
"font-family: Segoe Print;\n"
"font-size: 9pt;\n"
"}\n"
"\n"
"/*Убирает противные белые заголовочные полосы*/\n"
"QTableWidget QWidget\n"
"{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"\n"
"}\n"
"\n"
"/*Заголовки выбранной секции*/\n"
"QHeaderView::section:checked\n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 200),\n"
"stop:0.2 rgba(73, 216, 255, 150),\n"
"stop:1 rgba(73, 216, 255, 200) );\n"
"}\n"
"\n"
"/*Клетки таблицы*/\n"
"QTableWidget::item\n"
"{\n"
"padding-left: 4px;\n"
"text-align: center;\n"
"background: rgba(55, 255, 212, 100);\n"
"border: 2px solid rgba(16, 200, 255, 220);\n"
"border-radius: 5px;\n"
"margin: 1px;\n"
"}\n"
"\n"
"/*Выбранная клетка*/\n"
"QTableView::item::selected\n"
"{\n"
"    selection-background-color: #E6FFBF;\n"
"    selection-color:black;\n"
"}\n"
"\n"
"/*Наведённая клетка*/\n"
"QTableView::item::hover\n"
"{\n"
"    background-color: #C8EDFF;\n"
"    selection-color:black;\n"
"}\n"
"\n"
"/*Заголовки таблицы и */\n"
"/*Кусок таблицы слева сверху*/\n"
"QTableWidget QHeaderView::section,\n"
"QTableView QTableCornerButton::section\n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 200),\n"
"stop:0.2 rgba(87, 216, 255, 100),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"padding: 1px;\n"
"border: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"border-radius: 7px;\n"
"margin: 1px;\n"
"}\n"
"/*border-style: none; - убрать границы*/\n"
"\n"
"QTableWidget QHeaderView::section:vertical\n"
"{\n"
"padding-right: 0px;\n"
"padding-left: 10px;\n"
"}\n"
"\n"
"#mainWin\n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 100),\n"
"stop:1 rgba(61, 252, 255, 100) );\n"
"border: 8px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 150),\n"
"stop:1 rgba(159, 5, 255, 60) );\n"
"}\n"
"\n"
"#titleBar\n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 100),\n"
"stop:1 rgba(159, 5, 255, 100) );\n"
"border: 5px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(159, 5, 255, 40) );\n"
"}\n"
"\n"
"#tableWidget_table\n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(159, 5, 255, 155) );\n"
"border: 5px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(159, 5, 255, 40) );\n"
"}\n"
"\n"
"QFrame QFrame QPushButton\n"
"{\n"
"border: none;\n"
"}\n"
"\n"
"#pushButton_close\n"
"{\n"
"background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"stop: 0 #ff0000,\n"
"stop: 0.7 #ff9092,\n"
"stop: 1 rgba(255, 255, 255, 0) );\n"
"}\n"
"\n"
"#pushButton_hide\n"
"{\n"
"background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
"stop: 0 rgb(255, 167, 60),\n"
"stop: 0.7 rgb(255, 190, 76),\n"
"stop: 1 rgba(255, 255, 255, 0) );\n"
"}\n"
"\n"
"#pushButton_save, #pushButton_add, #pushButton_set\n"
"{\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 200),\n"
"stop:0.2 rgba(87, 216, 255, 150),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"padding: 1px;\n"
"border: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"    padding: 5px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#pushButton_add\n"
"{\n"
"border-radius:25px;\n"
"}\n"
"\n"
"#pushButton_save:hover, #pushButton_add:hover, #pushButton_set:hover\n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(255, 255, 255, 200),\n"
"stop:0.2 rgba(73, 216, 255, 150),\n"
"stop:1 rgba(73, 216, 255, 200) );\n"
"}\n"
"\n"
"#pushButton_save:pressed, #pushButton_add:pressed, #pushButton_set:pressed\n"
"{\n"
"    border-width: 4px;\n"
"}\n"
"\n"
"QScrollBar {\n"
"    border: 2px solid qlineargradient(spread:pad, y1:0, y2:1,\n"
"stop:0 rgba(64, 105, 255, 100),\n"
"stop:0.5 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 120) );\n"
"    width: 14px;\n"
"    margin: 24px 0 24px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"QScrollBar::handle {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(64, 105, 255, 200),\n"
"stop:0.5 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"border: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 rgba(64, 105, 255, 200),\n"
"stop:0.5 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line {\n"
"    background: qlineargradient(spread:pad, y1:0, y2:1,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"border: 2px solid qlineargradient(spread:pad, y1:0, y2:1,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"    height: 15px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line {\n"
"    background: qlineargradient(spread:pad, y1:1, y2:0,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"border: 2px solid qlineargradient(spread:pad, y1:1, y2:0,\n"
"stop:0 rgba(255, 255, 255, 255),\n"
"stop:1 rgba(64, 105, 255, 200) );\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    margin-bottom: 6px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainWin = QtWidgets.QFrame(self.centralwidget)
        self.mainWin.setGeometry(QtCore.QRect(0, 0, 1041+mrb, 556))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.mainWin.setFont(font)
        self.mainWin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainWin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainWin.setObjectName("mainWin")
        self.titleBar = QtWidgets.QFrame(self.mainWin)
        self.titleBar.setGeometry(QtCore.QRect(0, 0, 1041+mrb, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.titleBar.setFont(font)
        self.titleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.pushButton_close = QtWidgets.QPushButton(self.titleBar)
        self.pushButton_close.setGeometry(QtCore.QRect(1010+mrb, 10, 21, 21))
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_hide = QtWidgets.QPushButton(self.titleBar)
        self.pushButton_hide.setGeometry(QtCore.QRect(980+mrb, 10, 21, 21))
        self.pushButton_hide.setText("")
        self.pushButton_hide.setObjectName("pushButton_hide")
        self.label_appName = QtWidgets.QLabel(self.titleBar)
        self.label_appName.setGeometry(QtCore.QRect(43, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_appName.setFont(font)
        self.label_appName.setObjectName("label_appName")
        self.label = QtWidgets.QLabel(self.titleBar)
        self.label.setGeometry(QtCore.QRect(15, 10, 21, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./icons/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableWidget_table = QtWidgets.QTableWidget(self.mainWin)
        self.tableWidget_table.setGeometry(QtCore.QRect(20, 50, 1001+mrb, 441))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.tableWidget_table.setFont(font)
        self.tableWidget_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_table.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_table.setWordWrap(True)
        self.tableWidget_table.setCornerButtonEnabled(True)
        self.tableWidget_table.setObjectName("tableWidget_table")
        self.tableWidget_table.setColumnCount(8)
        self.tableWidget_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_table.setHorizontalHeaderItem(7, item)
        self.tableWidget_table.verticalHeader().setCascadingSectionResizes(False)
        self.pushButton_add = QtWidgets.QPushButton(self.mainWin)
        self.pushButton_add.setGeometry(QtCore.QRect(410, 494, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_save = QtWidgets.QPushButton(self.mainWin)
        self.pushButton_save.setGeometry(QtCore.QRect(934+mrb, 500, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_set = QtWidgets.QPushButton(self.mainWin)
        self.pushButton_set.setGeometry(QtCore.QRect(18, 500, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.pushButton_set.setFont(font)
        self.pushButton_set.setObjectName("pushButton_set")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_appName.setText(_translate("MainWindow", "AutoMeeter"))
        item = self.tableWidget_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "My Name"))
        item = self.tableWidget_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Iterance"))
        item = self.tableWidget_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Platform"))
        item = self.tableWidget_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Delete"))
        self.pushButton_add.setText(_translate("MainWindow", "Add new meeting"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_set.setText(_translate("MainWindow", "Last row to model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
